-- Find total customers by country
SELECT 
	country,
	COUNT(DISTINCT customer_key) AS Total_customers
FROM 
	gold.dim_customers
GROUP BY 
	country 
ORDER BY 
	COUNT(DISTINCT customer_key) DESC

-- Find total customers by gender 
SELECT 
	gender,
	COUNT(DISTINCT customer_key) AS Total_customers
FROM 
	gold.dim_customers
GROUP BY 
	gender 
ORDER BY 
	COUNT(DISTINCT customer_key) DESC

--Find total products by category
SELECT 
	category,
	COUNT(DISTINCT product_key) AS Total_products
FROM 
	gold.dim_products
GROUP BY 
	category
ORDER BY 
	COUNT(DISTINCT product_key) DESC

--What is the average cost in each category 
SELECT 
	category,
	AVG(product_cost) AS AVG_Cost
FROM 
	gold.dim_products 
GROUP BY 
	category
ORDER BY 
	AVG_Cost DESC

-- Total revenue genarated by each category 
SELECT 
	p.category,
	SUM(s.sales_amount) AS Total_revenue
FROM 
	gold.fact_sales s
	
LEFT JOIN
	gold.dim_products p
ON 
	p.product_key = s.product_key
GROUP BY 
	p.category
ORDER BY 
	Total_revenue

-- Total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS Total_revenue
FROM 
	 gold.fact_sales s
   
LEFT JOIN
    gold.dim_customers c
ON 
    c.customer_key = s.customer_key
GROUP BY 
    c.customer_key, c.first_name, c.last_name
ORDER BY 
    Total_revenue DESC;
	
-- What is the ditribution of sold items in accross the country
SELECT 
	c.country,
	SUM(s.quantity) AS Total_Sold_items
FROM
	gold.fact_sales s
	
LEFT JOIN
    gold.dim_customers c
ON 
    c.customer_key = s.customer_key
GROUP BY 
	c.country 
ORDER BY 
	Total_Sold_items DESC